---
- hosts: local
  become: yes
  vars:
    username: pavitpandher
    server_user: www-data
    server_group: www-data
    project_name: candidate
    project_path: /home/pavitpandher/code/shinecandidate
    virtualenv_path: /home/pavitpandher/Envs/candidate/
    uwsgi_virtual_path: /home/pavitpandher/Envs/uwsgi
    ruby_shims_path: /home/pavitpandher/.rbenv/shims
    nginx_port: 80
    domain: shine.com
    csm_path: /shineresume/CSM
    sitemaps_path: /sitemaps/sitemaps_xml
    sitemaps_path2: /sitemaps/sitemaps_listingpages
    sitemaps_job_path: /sitemaps/sitemaps_job
    browsejobs_path: /sitemaps/browsejobs
    browsejobs_path_new: /sitemaps/browsejobs_2016
    sitemaps_2016: /sitemaps/sitemaps_2016
    ssl_port: 443
    ssl_domain: mapi.shine.com
    er_project_name: 'employee_referral'
    er_project_path: /home/pavitpandher/code/shinereferral/project_referral
    er_virtualenv_path: /home/pavitpandher/Envs/referral/
    employee_referral_domain: er.shine.com
    employee_referral_server: http://127.0.0.1:9292
  roles:
    # - git
    # - sys_tweaks
    # - django_setup
    # - ruby_setup
    # - uwsgi
    - uwsgi_configuration
    # - nginx_setup
    #- nginx_configuration
    # - role: rvm_io.rvm1-ruby
    #   becomes: no
    #   tags: ruby
    #   rvm1_gpg_key_server: 'hkp://keys.gnupg.net:80'
    #   rvm1_install_path: "/home/{{ username }}/rvm"
    #   rvm1_rubies:
    #     - 'ruby-2.2.2'
