---
- name: Tweaking /etc/sysctl.conf
  lineinfile:
    dest=/etc/sysctl.conf
    regexp='(^{{ item.name }})|(^\n{{item.name}})'
    state=present
    line='\n{{ item.name }} = {{ item.value }}'
    insertafter=EOF
    backup=yes
  with_items:
    - { name: 'net.core.somaxconn', value: '65535'}
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: '1440000'}
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '3240000'}
    - { name: 'net.ipv4.ip_local_port_range', value: '1024 65000'}
    - { name: 'net.ipv4.tcp_window_scaling', value: '1'}
    - { name: 'net.ipv4.tcp_fin_timeout', value: '30'}

- name: Tweaking /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp='^\*{{ item.name }}'
    state=present
    line='\n* {{ item.name }} {{ item.value }}'
    insertafter=EOF
    backup=yes
  with_items:
    - { name: 'soft nofile', value: '50000'}
    - { name: 'hard nofile', value: '50000'}

- name: Restarting sysctl
  shell: sysctl -p
  become: yes
